type User @table {
  username: String!
  passwordHash: String!
  createdAt: Timestamp!
  email: String
}

type Message @table {
  content: String!
  createdAt: Timestamp!
  user: User
  title: String
  lastEditedAt: Timestamp
}